apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mistral-dsvc-nodeport
  namespace: maia
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30080
  selector:
    app: mistral
  type: NodePort

