---
apiVersion: v1
kind: Service
metadata:
  name: mistral-npu-service
  namespace: maia
spec:
  selector:
    app: mistral-npu
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
  type: LoadBalancer